//! The VM fixture: a complete Paperclip session made out of stand-ins.
//!
//! Three things are substituted, and nothing else:
//!
//! * **stock** — a stand-in unit, because `xochitl.service` exists only on the
//!   tablet, and because one of the §10 rows requires stock to *fail* to
//!   start, which is not something to arrange on a device whose `OnFailure=`
//!   lands on a serial console;
//! * **the sysfs wakelock files** — the VM has no `/sys/power/wake_lock`;
//! * **the apps** — `paper-fault-app` in place of Home and Chess;
//! * **the candidate platform releases** — `paper-fault-app` in place of
//!   `paperclip-host` inside a staged release, so a release can be made to
//!   stall on a chosen readiness rung. The *baseline* release is the real
//!   supervisor, so the healthy side of every upgrade case is the real thing
//!   climbing the real ladder.
//!
//! Everything else is real: real systemd, real cgroups, real signals, the real
//! generated units, and the real supervisor binary. The units in particular are
//! generated by the same [`paper_host::units`] code that runs on the device,
//! with only the stock unit name differing — so the harness is checking the
//! text that ships.

use std::fs;
use std::os::unix::fs::PermissionsExt as _;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::{Duration, Instant};

use paper_host::facilities::Facilities;
use paper_host::units::{
    APP_UNIT, HOST_UNIT, RESTORE_UNIT, SESSION_TARGET, SessionGrants, SessionPaths, SessionSpec,
    UnitSet,
};
use paper_packages::archive;
use paper_packages::publish::Publisher;
use paper_packages::signing::{Domain, SecretKey};
use paper_packages::store::Layout as AppStoreLayout;
use paper_packages::{Capability, InstallPolicy, InstalledApp, Manifest};
use paper_updater::bundle;
use paper_updater::layout::PlatformLayout;
use semver::Version;

/// The app id the §12 install cases publish and install.
pub(crate) const STORE_APP: &str = "dev.calum.storeapp";

/// The stand-in for `xochitl.service`.
pub(crate) const STOCK_UNIT: &str = "paperclip-harness-stock.service";

/// The unprivileged user sessions run as, created by the harness.
pub(crate) const SESSION_USER: &str = "paperclip";

/// The release the fixture installs as the known-good baseline.
///
/// Its `bin/paperclip-host` is the *real* supervisor, so "the fallback came
/// back" in an upgrade case means the real supervisor climbed the real ladder
/// — not that a stand-in said it had.
pub(crate) const BASELINE: &str = "0.1.0";

/// Where the fixture puts things.
#[derive(Debug, Clone)]
pub(crate) struct Fixture {
    /// Paths as the supervisor sees them.
    pub(crate) paths: SessionPaths,
    /// `/tmp/paperclip-harness`, standing in for the real `/tmp` the display
    /// locks live in. Still under `/tmp`, so `ProtectSystem=strict` leaves it
    /// writable exactly as it does on the device.
    pub(crate) locks_dir: PathBuf,
    /// Stand-in for `/sys/power`.
    pub(crate) power_dir: PathBuf,
    /// Where the built binaries were copied from.
    pub(crate) bin_dir: PathBuf,
    /// What this machine actually enforces.
    pub(crate) facilities: Facilities,
    /// The platform release tree, for the WWW-8 upgrade cases.
    pub(crate) platform: PlatformLayout,
    /// The app store root, for the §12 install cases. A sibling of
    /// `paths.root`, never nested inside it — an app store inside the
    /// platform root would let an app install reach the host, which is
    /// exactly the containment `PlatformLayout::separate_from` exists to
    /// refuse (see `platform/updater/tests/upgrade.rs`).
    pub(crate) appstore: AppStoreLayout,
    /// Where the §12 cases publish packages, read back through
    /// `paperctl install --catalog`.
    pub(crate) app_catalog_dir: PathBuf,
}

impl Fixture {
    /// Builds the fixture, installs the units, and leaves stock running.
    ///
    /// # Errors
    ///
    /// Any setup failure. There is no partial fixture: a case run against half
    /// a fixture would produce a result nobody should trust.
    pub(crate) fn build(bin_dir: &Path) -> Result<Self, String> {
        require_root()?;
        let facilities = paper_host::probe::probe().map_err(|error| error.to_string())?;

        let paths = SessionPaths {
            root: PathBuf::from("/opt/paperclip-harness"),
            runtime_units: PathBuf::from("/run/systemd/system"),
            state: PathBuf::from("/run/paperclip-harness"),
            storage: PathBuf::from("/opt/paperclip-harness/storage"),
        };
        let platform = PlatformLayout::new(&paths.root);
        let appstore = AppStoreLayout::new("/opt/paperclip-harness-appstore");
        let fixture = Self {
            paths,
            locks_dir: PathBuf::from("/tmp/paperclip-harness"),
            power_dir: PathBuf::from("/run/paperclip-harness/power"),
            bin_dir: bin_dir.to_path_buf(),
            facilities,
            platform,
            appstore,
            app_catalog_dir: PathBuf::from("/opt/paperclip-harness-appstore-catalog"),
        };

        fixture.make_user()?;
        fixture.make_directories()?;
        fixture.install_binaries()?;
        fixture.install_platform()?;
        fixture.install_appstore()?;
        fixture.write_config()?;
        fixture.install_units()?;
        fixture.stock_should_start()?;
        fixture.reset()?;
        Ok(fixture)
    }

    /// Puts the machine back to "stock is up, nothing of ours is running".
    ///
    /// # Errors
    ///
    /// If stock cannot be brought back, which makes every later case
    /// meaningless.
    pub(crate) fn reset(&self) -> Result<(), String> {
        let _ = systemctl(&["stop", SESSION_TARGET]);
        let _ = systemctl(&["stop", HOST_UNIT]);
        let _ = systemctl(&["reset-failed", HOST_UNIT]);
        let _ = systemctl(&["reset-failed", RESTORE_UNIT]);
        let _ = systemctl(&["reset-failed", STOCK_UNIT]);
        let _ = fs::remove_dir_all(self.paths.diagnostics());
        let _ = fs::remove_file(self.paths.state.join("survivors"));
        let _ = fs::remove_file(self.paths.state.join("status"));
        let _ = fs::remove_file(self.paths.state.join("command"));
        let _ = fs::remove_file(self.locks_dir.join("epframebuffer.lock"));
        // The start budget is shared and persisted, which is the point of it —
        // and which means a case would otherwise inherit the previous case's
        // recorded starts and be refused before it began.
        let _ = fs::remove_file(self.paths.state.join("xochitl-starts"));
        let _ = fs::remove_file(self.locks_dir.join("epd.lock"));
        let _ = fs::write(self.power_dir.join("wake_lock"), "");
        let _ = fs::write(self.power_dir.join("wake_unlock"), "");
        let _ = fs::remove_file(self.paths.state.join("stop"));
        // The upgrade cases move `current`, write a journal and leave extra
        // releases behind. A case that inherited any of that would be graded
        // against its predecessor's platform.
        self.restore_baseline()?;
        // The install cases do the same to the app store: a leftover journal
        // entry or a stray staging directory would make the next case's
        // recovery assertions meaningless.
        self.clear_appstore()?;
        self.stock_should_start()?;
        systemctl(&["start", STOCK_UNIT])?;
        if !wait(Duration::from_secs(10), || unit_active(STOCK_UNIT)) {
            return Err("the stand-in stock unit would not start".to_owned());
        }
        Ok(())
    }

    /// Tears the fixture down and leaves nothing of Paperclip behind, which is
    /// also the assertion behind the §10 "Reboot" row.
    pub(crate) fn teardown(&self) {
        let _ = systemctl(&["stop", SESSION_TARGET]);
        let _ = systemctl(&["stop", HOST_UNIT]);
        let _ = systemctl(&["stop", STOCK_UNIT]);
        for unit in self.unit_names() {
            let _ = fs::remove_file(self.paths.runtime_units.join(unit));
        }
        let _ = fs::remove_file(self.paths.runtime_units.join(STOCK_UNIT));
        let _ = systemctl(&["daemon-reload"]);
    }

    /// Every unit file the fixture installed.
    pub(crate) fn unit_names(&self) -> Vec<String> {
        self.units()
            .files
            .into_iter()
            .map(|file| file.name)
            .collect()
    }

    /// The generated units, exactly as the device would get them apart from
    /// the paths and the stock unit name.
    pub(crate) fn units(&self) -> UnitSet {
        let spec = self.spec();
        let app = installed_app();
        let grants = SessionGrants::derive(app.manifest().id(), app.capabilities(), &spec.paths);
        UnitSet::plan(&spec, &grants, &self.facilities)
    }

    fn spec(&self) -> SessionSpec {
        SessionSpec {
            paths: self.paths.clone(),
            user: SESSION_USER.to_owned(),
            display_locks: self.locks_dir.clone(),
            stock_unit: STOCK_UNIT.to_owned(),
            // The VM has no e-ink panel and no /dev/dri/card0. Keeping the
            // shape (DevicePolicy=closed plus an explicit allow list) matters;
            // keeping a device node that does not exist here would only make
            // systemd log a warning on every start.
            device_allow: vec![
                "/dev/null rw".to_owned(),
                "/dev/zero rw".to_owned(),
                "/dev/urandom r".to_owned(),
                "char-input r".to_owned(),
            ],
            limits: paper_host::units::SessionLimits {
                // Small enough that `memory-pressure` hits it in a second or
                // two, large enough that a healthy session never does.
                address_space_bytes: 192 * 1024 * 1024,
                tasks: 32,
                cpu_percent: None,
                log_burst: 200,
                log_interval_secs: 30,
            },
        }
    }

    /// The path a scenario's wrapper script goes at.
    pub(crate) fn app_wrapper(&self, name: &str) -> PathBuf {
        self.paths
            .root
            .join("apps")
            .join(name)
            .join("bin")
            .join(name)
    }

    /// Writes a wrapper that runs `paper-fault-app` with `arguments`.
    ///
    /// A wrapper rather than an argument on the unit, so the generated
    /// `ExecStart=` stays byte-for-byte what the device gets.
    ///
    /// # Errors
    ///
    /// If the script cannot be written or made executable.
    pub(crate) fn install_app(&self, name: &str, arguments: &[&str]) -> Result<(), String> {
        let path = self.app_wrapper(name);
        let parent = path.parent().ok_or("no parent directory")?;
        fs::create_dir_all(parent).map_err(|error| error.to_string())?;
        let progress = self.paths.progress().join(format!("app:{name}"));
        let lock = self.locks_dir.join("epframebuffer.lock");
        let script = format!(
            "#!/bin/sh\n\
             # Generated by the failure harness. Stands in for an installed app.\n\
             exec {fault} {arguments} --progress {progress} --lock {lock}\n",
            fault = self.paths.root.join("bin/paper-fault-app").display(),
            arguments = arguments.join(" "),
            progress = progress.display(),
            lock = lock.display(),
        );
        fs::write(&path, script).map_err(|error| error.to_string())?;
        fs::set_permissions(&path, fs::Permissions::from_mode(0o755))
            .map_err(|error| error.to_string())?;
        Ok(())
    }

    /// The unit a scenario's session runs under.
    pub(crate) fn app_unit(&self, name: &str) -> String {
        format!("paperclip-app@{name}.service")
    }

    /// Asks the supervisor to bring a session up.
    ///
    /// # Errors
    ///
    /// If the command file cannot be written.
    pub(crate) fn command(&self, command: &str) -> Result<(), String> {
        fs::write(self.paths.state.join("command"), command).map_err(|error| error.to_string())
    }

    /// The supervisor's own view of the world.
    pub(crate) fn status(&self) -> String {
        fs::read_to_string(self.paths.state.join("status")).unwrap_or_default()
    }

    /// One field out of the status file.
    pub(crate) fn status_field(&self, key: &str) -> Option<String> {
        self.status()
            .lines()
            .find_map(|line| line.strip_prefix(&format!("{key}=")))
            .map(str::to_owned)
    }

    /// Makes the next start of the stand-in stock unit fail.
    ///
    /// # Errors
    ///
    /// If the control file cannot be written.
    pub(crate) fn stock_should_fail(&self) -> Result<(), String> {
        fs::write(self.paths.state.join("stock-fails"), "1").map_err(|error| error.to_string())
    }

    /// Makes the stand-in stock unit start normally again.
    ///
    /// # Errors
    ///
    /// If the control file cannot be removed.
    pub(crate) fn stock_should_start(&self) -> Result<(), String> {
        match fs::remove_file(self.paths.state.join("stock-fails")) {
            Ok(()) => Ok(()),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
            Err(error) => Err(error.to_string()),
        }
    }

    fn make_user(&self) -> Result<(), String> {
        if Command::new("id")
            .arg(SESSION_USER)
            .output()
            .is_ok_and(|output| output.status.success())
        {
            return Ok(());
        }
        let status = Command::new("useradd")
            .args([
                "--system",
                "--no-create-home",
                "--shell",
                "/usr/sbin/nologin",
            ])
            .arg(SESSION_USER)
            .status()
            .map_err(|error| format!("useradd: {error}"))?;
        if status.success() {
            Ok(())
        } else {
            Err(format!("useradd {SESSION_USER} failed: {status}"))
        }
    }

    fn make_directories(&self) -> Result<(), String> {
        for directory in [
            &self.paths.root,
            &self.paths.state,
            &self.paths.storage,
            // The granted storage directory has to exist before the session
            // starts: `ReadWritePaths=` on a path that is not there is a hard
            // `226/NAMESPACE` failure, not a warning. On the device this is
            // created at install time.
            &self.paths.storage.join("dev.calum.harness"),
            &self.paths.progress(),
            &self.paths.diagnostics(),
            &self.locks_dir,
            &self.power_dir,
            &self.paths.root.join("bin"),
            &self.paths.root.join("apps"),
            &self.paths.root.join("bundles"),
        ] {
            fs::create_dir_all(directory)
                .map_err(|error| format!("{}: {error}", directory.display()))?;
        }
        // The session runs unprivileged and has to be able to publish progress
        // and write its granted storage.
        for directory in [&self.paths.progress(), &self.paths.storage, &self.locks_dir] {
            chown(directory, SESSION_USER)?;
        }
        fs::set_permissions(&self.locks_dir, fs::Permissions::from_mode(0o1777))
            .map_err(|error| error.to_string())?;
        Ok(())
    }

    /// Establishes the platform release tree and installs the baseline
    /// release, whose supervisor is the real one.
    fn install_platform(&self) -> Result<(), String> {
        self.platform
            .ensure()
            .map_err(|error| format!("platform root: {error}"))?;
        let secret = SecretKey::generate().map_err(|error| error.to_string())?;
        fs::write(
            self.platform.keys_dir().join("harness.key"),
            secret.to_armoured(),
        )
        .map_err(|error| error.to_string())?;
        fs::write(
            self.platform.keys_dir().join("harness.pub"),
            secret.public_key().to_armoured(),
        )
        .map_err(|error| error.to_string())?;
        self.stage_release(BASELINE, None)?;
        self.restore_baseline()
    }

    /// The signing key the fixture publishes bundles with.
    pub(crate) fn key(&self) -> SecretKey {
        fs::read_to_string(self.platform.keys_dir().join("harness.key"))
            .expect("the harness key was written at build time")
            .trim()
            .parse()
            .expect("the harness key round-trips")
    }

    /// The public key file `paperctl upgrade` is pointed at.
    pub(crate) fn trust_file(&self) -> PathBuf {
        self.platform.keys_dir().join("harness.pub")
    }

    /// Writes a release directory. `ladder` picks the stand-in supervisor's
    /// behaviour; `None` installs the real one.
    fn stage_release(&self, version: &str, ladder: Option<&str>) -> Result<(), String> {
        let release = self
            .platform
            .release_dir(&Version::parse(version).map_err(|error| error.to_string())?);
        let bin = release.join("bin");
        fs::create_dir_all(&bin).map_err(|error| error.to_string())?;

        let host = match ladder {
            None => self.bin_dir.join("paperclip-host"),
            Some(_) => self.bin_dir.join("paper-fault-app"),
        };
        copy_executable(&host, &bin.join("paperclip-host"))?;
        // Home, the App Store and Settings ship with the platform (§13 plus
        // this project's own decision). Real ELF binaries, because the
        // supervisor's `home` rung reads the header of the one it is given.
        for name in ["home", "app-store", "settings"] {
            copy_executable(&self.bin_dir.join("paper-fault-app"), &bin.join(name))?;
        }
        let extras: &[&str] = if let Some(ladder) = ladder {
            fs::write(release.join("ladder"), format!("{ladder}\n"))
                .map_err(|error| error.to_string())?;
            &["ladder"]
        } else {
            &[]
        };

        // A release directory is not a release without its signed manifest.
        // Placing the binaries and stopping there is what the harness did
        // first, and the upgrade cases correctly refused to reason about a
        // release whose state version nobody had declared.
        let manifest = bundle::describe(&release, &description(version, extras)?)
            .map_err(|error| error.to_string())?;
        let document = manifest.to_document();
        let signature = self.key().sign(Domain::PLATFORM, document.as_bytes());
        fs::write(
            release.join(paper_updater::manifest::MANIFEST_FILE_NAME),
            &document,
        )
        .map_err(|error| error.to_string())?;
        fs::write(
            release.join(paper_updater::manifest::SIGNATURE_FILE_NAME),
            signature.to_armoured(),
        )
        .map_err(|error| error.to_string())?;
        Ok(())
    }

    /// Points `current` back at the baseline and removes everything an upgrade
    /// case left behind.
    fn restore_baseline(&self) -> Result<(), String> {
        let baseline = Version::parse(BASELINE).map_err(|error| error.to_string())?;
        if !self.platform.release_dir(&baseline).is_dir() {
            self.stage_release(BASELINE, None)?;
        }
        self.platform
            .select(&self.platform.current(), &baseline)
            .map_err(|error| format!("selecting the baseline: {error}"))?;
        let _ = self.platform.deselect(&self.platform.previous());
        let _ = fs::remove_file(self.platform.journal_file());
        for version in self.platform.installed().unwrap_or_default() {
            if version != baseline {
                let _ = fs::remove_dir_all(self.platform.release_dir(&version));
            }
        }
        let _ = fs::remove_dir_all(self.platform.staging_dir());
        let _ = fs::create_dir_all(self.platform.staging_dir());
        Ok(())
    }

    /// Establishes the app store root and the catalog directory the §12
    /// cases publish into.
    fn install_appstore(&self) -> Result<(), String> {
        self.appstore
            .ensure()
            .map_err(|error| format!("app store root: {error}"))?;
        fs::create_dir_all(&self.app_catalog_dir).map_err(|error| error.to_string())
    }

    /// Wipes whatever the previous case's install left selected, staged or
    /// journalled, and wipes the catalog too — a case that inherited a
    /// published version could not tell "refused" from "already installed".
    fn clear_appstore(&self) -> Result<(), String> {
        let _ = fs::remove_dir_all(self.appstore.root());
        let _ = fs::remove_dir_all(&self.app_catalog_dir);
        self.install_appstore()
    }

    /// Builds and publishes a release of the harness's store app, padded with
    /// `payload_bytes` of incompressible data.
    ///
    /// The padding exists for `install-power-loss`: a package built only from
    /// its manifest and a one-line entrypoint installs faster than this
    /// process can observe and kill it, and a compressible payload would
    /// collapse back down to the same problem inside the `.paperpkg`.
    ///
    /// # Errors
    ///
    /// Any failure to build, archive or publish the package.
    pub(crate) fn publish_store_app(
        &self,
        version: &str,
        payload_bytes: usize,
    ) -> Result<(), String> {
        let source = self
            .paths
            .root
            .join("bundles")
            .join(format!("store-src-{version}"));
        let _ = fs::remove_dir_all(&source);
        fs::create_dir_all(source.join("bin")).map_err(|error| error.to_string())?;
        fs::create_dir_all(source.join("assets")).map_err(|error| error.to_string())?;
        fs::write(
            source.join("paper.toml"),
            format!(
                "[app]\nid = \"{STORE_APP}\"\nname = \"Harness Store App\"\n\
                 version = \"{version}\"\nprotocol = \"1.0\"\nentrypoint = \"bin/app\"\n\
                 assets = [\"assets/payload.bin\"]\n"
            ),
        )
        .map_err(|error| error.to_string())?;
        fs::write(source.join("bin/app"), format!("store app {version}"))
            .map_err(|error| error.to_string())?;
        fs::write(
            source.join("assets/payload.bin"),
            incompressible(payload_bytes),
        )
        .map_err(|error| error.to_string())?;

        let mut bytes = Vec::new();
        archive::build(&source, &mut bytes).map_err(|error| error.to_string())?;
        let package = self
            .paths
            .root
            .join("bundles")
            .join(format!("store-{version}.paperpkg"));
        fs::write(&package, &bytes).map_err(|error| error.to_string())?;

        let publisher = Publisher::open(&self.app_catalog_dir, "harness-store")
            .map_err(|error| error.to_string())?;
        publisher
            .publish(&package, &self.key(), "harness release", 1_000)
            .map_err(|error| error.to_string())?;
        Ok(())
    }

    /// Builds a signed bundle for `version` whose supervisor behaves as
    /// `ladder` says.
    ///
    /// # Errors
    ///
    /// Any failure to assemble, sign or write the bundle.
    pub(crate) fn bundle(&self, version: &str, ladder: &str) -> Result<PathBuf, String> {
        let source = self
            .paths
            .root
            .join("bundles")
            .join(format!("src-{version}-{ladder}"));
        let _ = fs::remove_dir_all(&source);
        fs::create_dir_all(source.join("bin")).map_err(|error| error.to_string())?;
        let host = if ladder == "real" {
            self.bin_dir.join("paperclip-host")
        } else {
            self.bin_dir.join("paper-fault-app")
        };
        copy_executable(&host, &source.join("bin/paperclip-host"))?;
        for name in ["home", "app-store", "settings"] {
            copy_executable(
                &self.bin_dir.join("paper-fault-app"),
                &source.join("bin").join(name),
            )?;
        }
        let extras: &[&str] = if ladder == "real" {
            &[]
        } else {
            fs::write(source.join("ladder"), format!("{ladder}\n"))
                .map_err(|error| error.to_string())?;
            &["ladder"]
        };

        let manifest = bundle::describe(&source, &description(version, extras)?)
            .map_err(|error| error.to_string())?;
        let document = manifest.to_document();
        let secret = self.key();
        let signature = secret.sign(Domain::PLATFORM, document.as_bytes());
        let path = self
            .paths
            .root
            .join("bundles")
            .join(format!("paperclip-{version}-{ladder}.tar.gz"));
        let file = fs::File::create(&path).map_err(|error| error.to_string())?;
        bundle::build(&source, &manifest, document.as_bytes(), &signature, file)
            .map_err(|error| error.to_string())?;
        Ok(path)
    }

    /// Runs `paperctl` with `arguments` and returns its output.
    ///
    /// The real command line, not the library: an upgrade case that called
    /// into `paper_updater` directly would be testing a code path nobody runs.
    ///
    /// # Errors
    ///
    /// If it could not be run. A non-zero exit is returned as an error
    /// carrying both streams, because several cases expect one.
    pub(crate) fn paperctl(&self, arguments: &[&str]) -> Result<String, String> {
        let output = Command::new(self.paths.root.join("bin/paperctl"))
            .args(arguments)
            .output()
            .map_err(|error| format!("paperctl {}: {error}", arguments.join(" ")))?;
        let stdout = String::from_utf8_lossy(&output.stdout).into_owned();
        let stderr = String::from_utf8_lossy(&output.stderr).into_owned();
        if output.status.success() {
            Ok(stdout)
        } else {
            Err(format!(
                "paperctl {} exited {}: {stdout}{stderr}",
                arguments.join(" "),
                output.status
            ))
        }
    }

    /// The arguments every upgrade command needs.
    pub(crate) fn upgrade_args(&self) -> [String; 4] {
        [
            "--root".to_owned(),
            self.paths.root.display().to_string(),
            "--state".to_owned(),
            self.paths.state.display().to_string(),
        ]
    }

    fn install_binaries(&self) -> Result<(), String> {
        for binary in ["paperclip-host", "paperctl", "paper-fault-app"] {
            let from = self.bin_dir.join(binary);
            let to = self.paths.root.join("bin").join(binary);
            // Unlink first. Copying over a binary that a process from the
            // previous run is still exiting from gives ETXTBSY; removing the
            // name leaves that process holding an inode nobody else can see,
            // which is exactly what we want.
            let _ = fs::remove_file(&to);
            fs::copy(&from, &to)
                .map_err(|error| format!("copy {} -> {}: {error}", from.display(), to.display()))?;
            fs::set_permissions(&to, fs::Permissions::from_mode(0o755))
                .map_err(|error| error.to_string())?;
        }
        // The stand-in for stock. It exists to be started and stopped, and to
        // be made to fail on demand — which is the only way to exercise the
        // "Xochitl fails to start" row anywhere it is safe to exercise.
        let stock = self.paths.root.join("bin/stock");
        fs::write(
            &stock,
            format!(
                "#!/bin/sh\n\
                 # Stand-in for xochitl.service.\n\
                 if [ -f {marker} ]; then\n\
                 \techo 'stock: refusing to start (harness marker present)' >&2\n\
                 \texit 1\n\
                 fi\n\
                 echo \"$$ stock\" > {lock}\n\
                 exec sleep infinity\n",
                marker = self.paths.state.join("stock-fails").display(),
                lock = self.locks_dir.join("epframebuffer.lock").display(),
            ),
        )
        .map_err(|error| error.to_string())?;
        fs::set_permissions(&stock, fs::Permissions::from_mode(0o755))
            .map_err(|error| error.to_string())?;
        Ok(())
    }

    fn write_config(&self) -> Result<(), String> {
        let config = format!(
            "# Written by the failure harness.\n\
             root = {root}\n\
             state = {state}\n\
             storage = {storage}\n\
             stock_unit = {stock}\n\
             start_budget = {budget}\n\
             locks_dir = {locks}\n\
             wakelock_dir = {power}\n\
             wakelock_name = paperclip-harness\n\
             switch_deadline_ms = 6000\n\
             progress_stall_ms = 2500\n\
             graceful_stop_ms = 2000\n\
             force_stop_ms = 3000\n\
             restore_deadline_ms = 8000\n\
             session_failures = 3\n\
             restore_attempts = 1\n",
            root = self.paths.root.display(),
            state = self.paths.state.display(),
            storage = self.paths.storage.display(),
            stock = STOCK_UNIT,
            budget = self.paths.state.join("xochitl-starts").display(),
            locks = self.locks_dir.display(),
            power = self.power_dir.display(),
        );
        fs::write(self.paths.state.join("config"), config).map_err(|error| error.to_string())
    }

    /// Writes every generated unit, plus the stand-in stock unit, and tells
    /// systemd to notice them.
    ///
    /// Called once by [`Self::build`], and again by any case that has to
    /// remove the units to prove something about their absence (WWW-74) —
    /// such a case must leave the fixture exactly as every other case here
    /// expects to find it, and this is how.
    pub(crate) fn install_units(&self) -> Result<(), String> {
        for file in self.units().files {
            let path = self.paths.runtime_units.join(&file.name);
            fs::write(&path, &file.contents)
                .map_err(|error| format!("{}: {error}", path.display()))?;
        }
        let stock_unit = format!(
            "[Unit]\n\
             Description=Harness stand-in for xochitl.service\n\
             # Mirrors the device's rate limit so a supervisor that retries too\n\
             # eagerly is caught here rather than on the tablet.\n\
             StartLimitIntervalSec=600\n\
             StartLimitBurst=4\n\
             \n\
             [Service]\n\
             Type=simple\n\
             ExecStart={stock}\n\
             # The same unprivileged user as a Paperclip session, because that\n\
             # is the device: the vendor's own `xochitl` runs as uid 500 and\n\
             # Paperclip sessions run as that same uid. Running the stand-in as\n\
             # root instead makes the ownership-registry file root-owned, and\n\
             # the session can then never claim the display — which is a\n\
             # property of the fixture, not of the product, and cost an\n\
             # afternoon to tell apart.\n\
             User={user}\n\
             Restart=no\n",
            stock = self.paths.root.join("bin/stock").display(),
            user = SESSION_USER,
        );
        fs::write(self.paths.runtime_units.join(STOCK_UNIT), stock_unit)
            .map_err(|error| error.to_string())?;
        systemctl(&["daemon-reload"])?;
        Ok(())
    }
}

/// The fixture's release description: protocol `CURRENT`, state version 1, and
/// whatever extras the caller ships.
fn description<'a>(
    version: &str,
    extras: &'a [&'a str],
) -> Result<bundle::Description<'a>, String> {
    Ok(bundle::Description {
        version: Version::parse(version).map_err(|error| error.to_string())?,
        protocol: paper_protocol::CURRENT,
        published: 0,
        state_version: 1,
        rollback_to_state: 1,
        notes: String::new(),
        extras,
    })
}

/// Copies a binary and makes it executable.
///
/// Unlinks first: copying over a binary a process from the previous case is
/// still exiting from gives `ETXTBSY`, and removing the name leaves that
/// process holding an inode nobody else can see.
fn copy_executable(from: &Path, to: &Path) -> Result<(), String> {
    let _ = fs::remove_file(to);
    fs::copy(from, to)
        .map_err(|error| format!("copy {} -> {}: {error}", from.display(), to.display()))?;
    fs::set_permissions(to, fs::Permissions::from_mode(0o755)).map_err(|error| error.to_string())
}

fn installed_app() -> InstalledApp {
    let manifest = Manifest::parse(
        "[app]\nid = \"dev.calum.harness\"\nname = \"Harness\"\nversion = \"0.1.0\"\n\
         protocol = \"1.0\"\nentrypoint = \"bin/harness\"\n",
    )
    .expect("the harness manifest is valid");
    let mut policy = InstallPolicy::deny_all();
    policy.allow(manifest.id(), Capability::Storage);
    InstalledApp::install(manifest, &policy)
}

/// `len` bytes that gzip cannot shrink meaningfully, so a package built from
/// them takes real wall-clock time to write, hash and extract instead of
/// collapsing to a few bytes on the wire.
fn incompressible(len: usize) -> Vec<u8> {
    let mut state: u64 = 0x9e37_79b9_7f4a_7c15;
    let mut bytes = Vec::with_capacity(len);
    while bytes.len() < len {
        state ^= state << 13;
        state ^= state >> 7;
        state ^= state << 17;
        bytes.extend_from_slice(&state.to_le_bytes());
    }
    bytes.truncate(len);
    bytes
}

fn chown(path: &Path, user: &str) -> Result<(), String> {
    let status = Command::new("chown")
        .arg("-R")
        .arg(format!("{user}:{user}"))
        .arg(path)
        .status()
        .map_err(|error| error.to_string())?;
    if status.success() {
        Ok(())
    } else {
        Err(format!("chown {} failed: {status}", path.display()))
    }
}

fn require_root() -> Result<(), String> {
    if !cfg!(target_os = "linux") {
        return Err("this harness only means anything on Linux".to_owned());
    }
    let uid = Command::new("id")
        .arg("-u")
        .output()
        .map_err(|error| error.to_string())?;
    let uid = String::from_utf8_lossy(&uid.stdout).trim().to_owned();
    if uid == "0" {
        Ok(())
    } else {
        Err(format!(
            "the harness starts and stops systemd units, so it needs root; running as uid {uid}"
        ))
    }
}

/// Runs `systemctl` with `arguments`.
///
/// # Errors
///
/// If it could not be run, or ran and failed.
pub(crate) fn systemctl(arguments: &[&str]) -> Result<String, String> {
    let output = Command::new("systemctl")
        .args(arguments)
        .output()
        .map_err(|error| format!("systemctl {}: {error}", arguments.join(" ")))?;
    if output.status.success() {
        Ok(String::from_utf8_lossy(&output.stdout).trim().to_owned())
    } else {
        Err(format!(
            "systemctl {} failed ({}): {}",
            arguments.join(" "),
            output.status,
            String::from_utf8_lossy(&output.stderr).trim()
        ))
    }
}

/// One systemd property, or an empty string.
pub(crate) fn property(unit: &str, name: &str) -> String {
    systemctl(&["show", unit, "--property", name, "--value"]).unwrap_or_default()
}

/// Whether `unit` is active.
pub(crate) fn unit_active(unit: &str) -> bool {
    property(unit, "ActiveState") == "active"
}

/// The pids inside a unit's cgroup, recursively.
pub(crate) fn unit_pids(unit: &str) -> Vec<u32> {
    let control = property(unit, "ControlGroup");
    if control.is_empty() {
        return Vec::new();
    }
    let root = Path::new("/sys/fs/cgroup").join(control.trim_start_matches('/'));
    let mut found = Vec::new();
    let mut pending = vec![root];
    while let Some(directory) = pending.pop() {
        if let Ok(raw) = fs::read_to_string(directory.join("cgroup.procs")) {
            found.extend(
                raw.lines()
                    .filter_map(|line| line.trim().parse::<u32>().ok()),
            );
        }
        if let Ok(entries) = fs::read_dir(&directory) {
            for entry in entries.flatten() {
                if entry.file_type().is_ok_and(|kind| kind.is_dir()) {
                    pending.push(entry.path());
                }
            }
        }
    }
    found
}

/// Whether a process exists.
pub(crate) fn alive(pid: u32) -> bool {
    Path::new("/proc").join(pid.to_string()).exists()
}

/// Polls `predicate` until it holds or `budget` runs out.
pub(crate) fn wait(budget: Duration, predicate: impl Fn() -> bool) -> bool {
    let deadline = Instant::now() + budget;
    loop {
        if predicate() {
            return true;
        }
        if Instant::now() >= deadline {
            return false;
        }
        std::thread::sleep(Duration::from_millis(100));
    }
}

/// The template unit name, for assertions that quote it.
pub(crate) const APP_TEMPLATE: &str = APP_UNIT;
