//! The two persistent units autostart needs, and why they are not beside
//! `platform/host`'s (WWW-53, §10).
//!
//! `platform/host::units` generates runtime-only units under
//! `/run/systemd/system`, rewritten at session start and gone at the next
//! reboot — that module's own doc comment says so as the whole point of it
//! (ADR-0008). These two are the opposite on purpose: they decide *whether*
//! a session gets a boot at all, so they have to survive the boot they are
//! deciding about. ADR-0008's WWW-53 amendment records what that costs and
//! why it is bought back deliberately rather than lost by accident.
//!
//! # Where these actually get installed
//!
//! Generating the text is all this module does. Writing it to the device's
//! root filesystem — `mount -o remount,rw /`, write, `mount -o remount,ro /`
//! — is a human action at the tablet, not something this crate or any agent
//! run performs; see WWW-53's result comment for exactly what is proven here
//! (the text, and the decision logic, in the VM harness) versus what still
//! needs that session.

use std::path::Path;
use std::time::Duration;

use paper_device::stock::STOCK_UNIT;
use paper_host::units::SessionPaths;

/// The persistent launcher unit's name.
pub const LAUNCHER_UNIT: &str = "paperclip-launcher.service";

/// The safe-mode oneshot's name.
pub const SAFE_MODE_UNIT: &str = "paperclip-safe-mode.service";

/// How long the launcher may go without petting systemd's watchdog.
///
/// Derived, not chosen, the same way [`paper_host::units::HOST_WATCHDOG`] is:
/// `paper_updater::health::CLIMB_DEADLINE` (30s — the supervisor's own climb
/// to `ready`) plus the Switch budget `docs/recovery.md` records (8s — the
/// internal deadline for a foreground switch to complete) plus margin for
/// the parts of a real display takeover neither budget covers on its own.
/// Sixty seconds is comfortably above the sum without being close to
/// `paper_host::units::HOST_WATCHDOG` (80s), which times a different thing
/// (a restore) and must stay free to mean that.
pub const LAUNCHER_WATCHDOG: Duration = Duration::from_secs(60);

const HEADER: &str = "# Generated by paper_boot::units.\n\
                      # Persistent, on the device's root filesystem — NOT written into\n\
                      # /run/systemd/system, and NOT rewritten at session start.\n\
                      # Installed exactly once by a human at the tablet, per ADR-0008's\n\
                      # WWW-53 amendment. Never by an update, and never by this crate.\n";

/// `paperclip-launcher.service` — generated text.
///
/// `disable_marker` and `paths` are threaded through rather than assumed to
/// be [`SessionPaths::device`]/[`crate::autostart::path`], so a test — or the
/// VM harness — can generate the exact unit it is about to install under a
/// temporary root.
pub fn launcher_service(paths: &SessionPaths, disable_marker: &Path) -> String {
    format!(
        "{HEADER}\n\
         [Unit]\n\
         Description=Paperclip: decide whether to start this boot\n\
         # The boot-time skip, enforced twice: here, so a device an operator\n\
         # has disabled never even execs the launcher binary, and again\n\
         # inside it (paper_boot::autostart::is_disabled), so `paperctl\n\
         # autostart disable` takes effect without a unit reload. A\n\
         # Condition= failure is not a start attempt and does not count\n\
         # against StartLimitBurst= below.\n\
         ConditionPathExists=!{marker}\n\
         After={stock}\n\
         # Never OnFailure=paperclip-restore-stock.service: stock is already\n\
         # up at this point — it is the vendor's own default — and starting\n\
         # it again here would be a second start against the very budget\n\
         # ADR-0012 shares with the supervisor's own recovery path.\n\
         OnFailure={safe_mode}\n\
         # Five crashes inside five minutes, then OnFailure= above. Systemd's\n\
         # own rate limiter, distinct from and much faster than the durable\n\
         # boot counter — this catches a launcher that crash-loops within a\n\
         # single boot; the counter catches one that starts cleanly each\n\
         # time but never reaches Home across several.\n\
         StartLimitIntervalSec=300\n\
         StartLimitBurst=5\n\
         \n\
         [Service]\n\
         Type=notify\n\
         NotifyAccess=main\n\
         ExecStart={launcher}\n\
         # Catches the launcher crashing outright — a bug, not a graded\n\
         # failure. A launcher that starts the supervisor, watches it fail\n\
         # to reach Home, records that in the durable counter and exits 0\n\
         # is a *successful* run: Restart= never fires for that case, because\n\
         # the retry policy across boots is the counter's job, not systemd's.\n\
         Restart=on-failure\n\
         # The default is 100ms — a respawn storm on flash.\n\
         RestartSec=2s\n\
         WatchdogSec={watchdog}s\n\
         KillMode=control-group\n\
         TimeoutStopSec=10s\n\
         \n\
         [Install]\n\
         WantedBy=multi-user.target\n",
        marker = disable_marker.display(),
        stock = STOCK_UNIT,
        safe_mode = SAFE_MODE_UNIT,
        launcher = paths.launcher().display(),
        watchdog = LAUNCHER_WATCHDOG.as_secs(),
    )
}

/// `paperclip-safe-mode.service` — generated text.
///
/// Its whole job is to set the same marker [`crate::autostart::disable`]
/// would, so a device that exceeded the launcher's own start limit — five
/// crashes in five minutes, a case the durable counter alone would take up
/// to three *boots* to catch — stops trying immediately instead of
/// continuing to crash-loop the launcher unit for the rest of this boot.
/// Nothing here touches `sshd` or `xochitl.service`: neither is supervised
/// by Paperclip, both are already up by the time this can possibly run, and
/// safe mode's whole point is that the one thing it does not depend on is
/// anything Paperclip supervises.
pub fn safe_mode_service(disable_marker: &Path) -> String {
    format!(
        "{HEADER}\n\
         [Unit]\n\
         Description=Paperclip: safe mode (autostart gave up this boot)\n\
         DefaultDependencies=no\n\
         \n\
         [Service]\n\
         Type=oneshot\n\
         RemainAfterExit=yes\n\
         ExecStart=/bin/sh -c 'echo \"safe mode: {launcher_unit} exceeded its start \\\n\
         limit\" > {marker}'\n\
         \n\
         [Install]\n\
         WantedBy=multi-user.target\n",
        launcher_unit = LAUNCHER_UNIT,
        marker = disable_marker.display(),
    )
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use super::*;

    fn paths() -> SessionPaths {
        SessionPaths::under(&PathBuf::from("/tmp/paperclip-boot-units-test"))
    }

    #[test]
    fn the_launcher_unit_names_the_launcher_binary_and_the_disable_marker() {
        let marker = PathBuf::from("/home/root/paperclip/autostart-disabled");
        let unit = launcher_service(&paths(), &marker);
        assert!(unit.contains(&paths().launcher().display().to_string()));
        assert!(unit.contains("ConditionPathExists=!/home/root/paperclip/autostart-disabled"));
        assert!(unit.contains("Restart=on-failure"));
        assert!(unit.contains("StartLimitBurst=5"));
        assert!(unit.contains("StartLimitIntervalSec=300"));
        assert!(unit.contains("WatchdogSec=60s"));
        assert!(unit.contains(&format!("OnFailure={SAFE_MODE_UNIT}")));
        assert!(unit.contains("[Install]"));
        assert!(unit.contains("WantedBy=multi-user.target"));
    }

    #[test]
    fn the_launcher_unit_never_names_data_as_the_marker_location() {
        // The whole point of ADR-0008's WWW-53 amendment: the vendor's own
        // `/data/internal/...` precedent motivated the *pattern*, never the
        // location. Assert it structurally so a future edit that reaches for
        // the vendor path by habit fails a test instead of shipping.
        let marker = PathBuf::from("/home/root/paperclip/autostart-disabled");
        let unit = launcher_service(&paths(), &marker);
        assert!(!unit.contains("/data/"));
    }

    #[test]
    fn the_safe_mode_unit_writes_the_same_marker_path_it_is_given() {
        let marker = PathBuf::from("/home/root/paperclip/autostart-disabled");
        let unit = safe_mode_service(&marker);
        assert!(unit.contains("/home/root/paperclip/autostart-disabled"));
        assert!(unit.contains("RemainAfterExit=yes"));
        assert!(!unit.contains("/data/"));
    }
}
